from __future__ import annotations

import pandas as pd

from src.utils import display_value, markdown_escape

PAPER_EXPORT_COLUMNS = [
    "id", "source", "paper_id", "title", "authors", "year", "publication_date", "venue", "journal",
    "field", "category", "project", "paper_type", "priority", "triage_score", "triage_reason", "keywords",
    "reading_time_estimate", "impact_factor", "affiliations", "auto_tags", "abstract", "translated_abstract",
    "doi", "url", "citation_count", "status", "notes", "pdf_path", "created_at", "updated_at",
]

VOCAB_EXPORT_COLUMNS = [
    "id", "word", "meaning", "source_title", "example_sentence", "context", "notes", "difficulty", "familiarity",
    "review_interval", "ease_factor", "review_count", "correct_count", "wrong_count", "last_review_at", "next_review_at",
    "created_at",
]

MATRIX_COLUMNS = [
    "paper_id", "title", "authors", "year", "journal", "project", "category", "paper_type", "priority", "keywords",
    "research_question", "method", "data", "findings", "limitations", "reusable_points", "citation_usage",
    "personal_judgement", "rating", "status",
]


def _to_csv_bytes(rows: list[dict], columns: list[str]) -> bytes:
    df = pd.DataFrame(rows)
    if df.empty:
        df = pd.DataFrame(columns=columns)
    else:
        visible = [col for col in columns if col in df.columns]
        df = df[visible]
    return df.to_csv(index=False, encoding="utf-8-sig").encode("utf-8-sig")


def papers_to_csv_bytes(papers: list[dict]) -> bytes:
    return _to_csv_bytes(papers, PAPER_EXPORT_COLUMNS)


def vocabulary_to_csv_bytes(words: list[dict]) -> bytes:
    return _to_csv_bytes(words, VOCAB_EXPORT_COLUMNS)


def matrix_to_csv_bytes(cards: list[dict]) -> bytes:
    return _to_csv_bytes(cards, MATRIX_COLUMNS)


def papers_to_markdown(papers: list[dict]) -> str:
    lines = [
        "# PaperMate Literature Library",
        "",
        "| ID | Title | Year | Journal | Project | Type | Priority | Score | Category | Status | DOI | Notes |",
        "|---:|---|---:|---|---|---|---|---:|---|---|---|---|",
    ]
    for paper in papers:
        lines.append(
            "| {id} | {title} | {year} | {journal} | {project} | {paper_type} | {priority} | {triage_score} | {category} | {status} | {doi} | {notes} |".format(
                id=paper.get("id", ""),
                title=markdown_escape(paper.get("title")),
                year=display_value(paper.get("year")),
                journal=markdown_escape(paper.get("journal") or paper.get("venue")),
                project=markdown_escape(paper.get("project")),
                paper_type=markdown_escape(paper.get("paper_type")),
                priority=markdown_escape(paper.get("priority")),
                triage_score=display_value(paper.get("triage_score")),
                category=markdown_escape(paper.get("category")),
                status=markdown_escape(paper.get("status")),
                doi=markdown_escape(paper.get("doi")),
                notes=markdown_escape(paper.get("notes")),
            )
        )
    lines.append("")
    lines.append("Generated by PaperMate Lit Assistant.")
    return "\n".join(lines)


def reading_notes_to_markdown(paper: dict, notes: list[dict], card: dict | None = None) -> str:
    title = display_value(paper.get("title"))
    lines = [f"# Reading Notes: {title}", ""]
    lines.append(f"- Authors: {display_value(paper.get('authors'))}")
    lines.append(f"- Year: {display_value(paper.get('year'))}")
    lines.append(f"- Journal: {display_value(paper.get('journal') or paper.get('venue'))}")
    lines.append(f"- Project: {display_value(paper.get('project'))}")
    lines.append(f"- Type/Priority: {display_value(paper.get('paper_type'))} / {display_value(paper.get('priority'))}")
    lines.append(f"- DOI: {display_value(paper.get('doi'))}")
    lines.append(f"- URL: {display_value(paper.get('url'))}")
    lines.append("")

    lines.append("## Abstract")
    lines.append(display_value(paper.get("abstract")))
    lines.append("")
    if display_value(paper.get("translated_abstract")) != "N/A":
        lines.append("## Abstract Translation")
        lines.append(display_value(paper.get("translated_abstract")))
        lines.append("")

    if card:
        lines.append("## Structured Reading Card")
        fields = [
            ("Research question", "research_question"),
            ("Method", "method"),
            ("Data", "data"),
            ("Findings", "findings"),
            ("Limitations", "limitations"),
            ("Reusable points", "reusable_points"),
            ("Citation usage", "citation_usage"),
            ("Personal judgement", "personal_judgement"),
        ]
        for label, key in fields:
            lines.append(f"### {label}")
            lines.append(display_value(card.get(key)))
            lines.append("")

    lines.append("## Free Notes")
    if not notes:
        lines.append("No notes yet.")
    for note in notes:
        lines.append(f"### {display_value(note.get('note_type'))} · {display_value(note.get('created_at'))}")
        if display_value(note.get("page")) != "N/A":
            lines.append(f"- Page/section: {display_value(note.get('page'))}")
        if display_value(note.get("quote")) != "N/A":
            lines.append(f"> {display_value(note.get('quote'))}")
        lines.append(display_value(note.get("note")))
        lines.append("")
    return "\n".join(lines)


def literature_matrix_to_markdown(cards: list[dict]) -> str:
    lines = [
        "# Literature Matrix",
        "",
        "| Paper | Year | Project | Type | Priority | Method | Data | Findings | Limitations | Reusable points |",
        "|---|---:|---|---|---|---|---|---|---|---|",
    ]
    for card in cards:
        lines.append(
            "| {title} | {year} | {project} | {paper_type} | {priority} | {method} | {data} | {findings} | {limitations} | {reusable_points} |".format(
                title=markdown_escape(card.get("title")),
                year=display_value(card.get("year")),
                project=markdown_escape(card.get("project")),
                paper_type=markdown_escape(card.get("paper_type")),
                priority=markdown_escape(card.get("priority")),
                method=markdown_escape(card.get("method")),
                data=markdown_escape(card.get("data")),
                findings=markdown_escape(card.get("findings")),
                limitations=markdown_escape(card.get("limitations")),
                reusable_points=markdown_escape(card.get("reusable_points")),
            )
        )
    return "\n".join(lines)


def weekly_report_to_markdown(start_date: str, end_date: str, cards: list[dict], notes: list[dict], translations: list[dict]) -> str:
    lines = [f"# Weekly Reading Report ({start_date} to {end_date})", ""]
    lines.append("## 1. Reading progress")
    lines.append(f"- Structured reading cards updated: {len(cards)}")
    lines.append(f"- Free notes added: {len(notes)}")
    lines.append(f"- Translation exercises saved: {len(translations)}")
    lines.append("")

    lines.append("## 2. Updated reading cards")
    if not cards:
        lines.append("No structured cards in this period.")
    for card in cards:
        lines.append(f"### {display_value(card.get('title'))}")
        lines.append(f"- Project: {display_value(card.get('project'))}")
        lines.append(f"- Type/Priority: {display_value(card.get('paper_type'))} / {display_value(card.get('priority'))}")
        lines.append(f"- Method: {display_value(card.get('method'))}")
        lines.append(f"- Reusable point: {display_value(card.get('reusable_points'))}")
        lines.append("")

    lines.append("## 3. Notes")
    if not notes:
        lines.append("No free notes in this period.")
    for note in notes:
        lines.append(f"- **{display_value(note.get('paper_title'))}** [{display_value(note.get('note_type'))}]: {display_value(note.get('note'))}")
    lines.append("")

    lines.append("## 4. Translation practice")
    if not translations:
        lines.append("No translation practice saved recently.")
    for item in translations[:10]:
        lines.append(f"- {display_value(item.get('paper_title'))}: score {display_value(item.get('self_score'))}/5")
    lines.append("")
    lines.append("## 5. Next actions")
    lines.append("- Pick 1-2 high-priority papers for deep reading.")
    lines.append("- Convert reusable points into review paragraphs or project design notes.")
    lines.append("- Review due vocabulary before the next reading session.")
    return "\n".join(lines)
